mentorcoin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('mentorcoin_app.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mentorcoin_app/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import RedirectView

from . import views

urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('', views.main, name="main"),
    path('code-review/create/', views.code_review_create, name="code_review_create"),
    path('code-review/detail/<int:pk>', views.CodeReviewDetail.as_view(), name="code_review_detail"),
    path('code-review/list', views.CodeReviewList.as_view(), name="code_review_list"),
    path('code-review/<int:pk>/claim', views.claim_code_review, name="claim_code_review"),
    path('code-review/<int:pk>/unclaim', views.unclaim_code_review, name="unclaim_code_review"),
    path('code-review/<int:pk>/fulfill', views.fulfill_code_review, name="fulfill_code_review")
    ]

mentorcoin_app/models.py
from django.db import models, transaction
from django import forms
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import MinValueValidator
from decimal import Decimal, getcontext

class CodeReview(models.Model):

	expires_choices = (
		(259200, '3 Days'),
		(604800, '1 Week'),
		(2592000, '1 Month'),
		(9999999999, 'Never')
	)

	experience_choices = (
		('Beginner', 'Beginner'),
		('Intermediate', 'Intermediate'),
		('Expert', 'Expert'),
	)

	length_choices = (
		('Hours', 'Hours'),
		('Days', 'Days'),
		('Weeks', 'Weeks')
	)

	status_choices = (
		('open', 'open'),
		('claimed', 'claimed'),
		('fulfilled', 'fulfilled'),
		('closed', 'closed'),
	)

	pr_title = models.CharField(max_length=100)
	pr_url = models.URLField()
	submitted_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name="code_reviews_submitted")
	notification_email = models.EmailField()
	full_name = models.CharField(max_length=200)
	amount = models.DecimalField(max_digits=9, decimal_places=3)
	description = models.TextField(blank=True)
	keywords = models.CharField(blank=True, max_length=500)
	expires = models.IntegerField(default=2592000, choices=expires_choices)
	experience_level = models.CharField(default="Beginner", choices=experience_choices, max_length=36)
	project_length = models.CharField(default="Hours", choices=length_choices, max_length=24)
	status = models.CharField(default='open', choices=status_choices, max_length=12)
	claimed_by = models.ForeignKey(User, null=True, on_delete=None, related_name="code_reviews_claimed")
	created = models.DateTimeField(auto_now_add=True)

	class Meta:
		ordering = ['-created']

mentorcoin_app/forms.py
from django import forms
from . import models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.core.validators import RegexValidator, FileExtensionValidator
from django.db.models import Q
from django.contrib.auth.models import User


class CodeReviewCreateForm(forms.ModelForm):

	amount = forms.FloatField(label="Amount (ETH)", min_value=.001)
	pr_url = forms.URLField(label="Pull Request URL")
	pr_title = forms.CharField(label="Pull Request Title")

	class Meta:
		model = models.CodeReview
		fields = "__all__"
		exclude = ['submitted_by', 'claimed_by', 'status']


class CodeReviewFulfillForm(forms.Form):
	description = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'rows': 5}))

mentorcoin_app/views.py
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.urls import reverse_lazy
from django.shortcuts import redirect, render, get_object_or_404
from django.http.response import HttpResponse, JsonResponse, HttpResponseNotFound
from django.contrib.auth.decorators import user_passes_test, login_required
from django.contrib import messages

from . import models, forms

@login_required
def code_review_create(request):

    if request.method == 'POST':
        form = forms.CodeReviewCreateForm(request.POST)

        code_review = models.CodeReview(
            pr_title=request.POST['pr_title'],
            pr_url = request.POST['pr_url'],
            submitted_by = request.user,
            notification_email = request.POST['notification_email'],
            full_name = request.POST['full_name'],
            amount = request.POST['amount'],
            description = request.POST['description'],
            keywords = request.POST['keywords'],
            expires = request.POST['expires'],
            experience_level = request.POST['experience_level'],
            project_length = request.POST['project_length'],
            status='open'
        )
        code_review.save()

        messages.add_message(
                request,
                messages.SUCCESS,
                'Code Review Request successfully created!'
            )

        return redirect(reverse_lazy('code_review_list'))

    else:
        form = forms.CodeReviewCreateForm()


    return render(
        request,
        'code_review_form.html',
        {
            'form': form
        }
    ) 


@login_required
def claim_code_review(request, pk):
    code_review = get_object_or_404(models.CodeReview, pk=pk)

    if code_review.status != 'open' or code_review.claimed_by:
        messages.add_message(
                request,
                messages.ERROR,
                'This Code Review Request has already been claimed or closed.'
            )
    else:
        code_review.status = 'claimed'
        code_review.claimed_by = request.user
        code_review.save()

        messages.add_message(
                request,
                messages.SUCCESS,
                'Code Review Request successfully claimed!'
            )


    return redirect(reverse_lazy('code_review_list'))


@login_required
def unclaim_code_review(request, pk):
    code_review = get_object_or_404(models.CodeReview, pk=pk)

    if code_review.status == 'open' or code_review.claimed_by != request.user:
        messages.add_message(
                request,
                messages.ERROR,
                "You can't unclaim this Code Review Request."
            )
    else:
        code_review.status = 'open'
        code_review.claimed_by = None
        code_review.save()

        messages.add_message(
                request,
                messages.SUCCESS,
                'Code Review Request successfully unclaimed.'
            )

    
    return redirect(reverse_lazy('code_review_list'))


@login_required
def fulfill_code_review(request, pk):
    code_review = get_object_or_404(models.CodeReview, pk=pk)

    if request.method == 'POST':
        form = forms.CodeReviewFulfillForm(request.POST)

        code_review.status = 'fulfilled'
        code_review.save()

        messages.add_message(
                request,
                messages.SUCCESS,
                'Code Review Request successfully fulfilled! Once the submitter accepts it, the bounty will be paid.'
            )

        return redirect(reverse_lazy('code_review_list'))

    else:
        form = forms.CodeReviewFulfillForm()


    return render(
        request,
        'code_review_fulfill_form.html',
        {
            'form': form,
            'code_review': code_review
        }
    ) 

class CodeReviewDetail(DetailView):
    model = models.CodeReview
    template_name = 'code_review_detail.html'


class CodeReviewList(ListView):
    model = models.CodeReview
    template_name = 'code_review_list.html'

    def total_number_open(self):
        code_reviews = models.CodeReview.objects.filter(status='open')
        return len(code_reviews)
    
    def total_amount_open(self):
        code_reviews = models.CodeReview.objects.filter(status='open')
        total_amount = 0
        for cr in code_reviews:
            total_amount += cr.amount

        return total_amount

    def total_number_claimed(self):
        code_reviews = models.CodeReview.objects.filter(status='claimed')
        return len(code_reviews)
    
    def total_amount_claimed(self):
        code_reviews = models.CodeReview.objects.filter(status='claimed')
        total_amount = 0
        for cr in code_reviews:
            total_amount += cr.amount

        return total_amount

def main(request):

    return render(
        request,
        'main.html',
        {'bodyClass': 'home'}
        )

mentorcoin_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block head_title %}MentorCoin{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    {% block config %}
      <script>
        var activeNav;
      </script>
    {% endblock %}

    {% block head_links %}
        <link rel="stylesheet" href="{% static 'vendor/bootstrap.min.css' %}">
        <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'vendor/buttons/bootstrap-social.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        <script src="{% static 'vendor/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/bignumber.js' %}"></script>
    {% endblock %}


    </head>
    <body style="padding-top:120px" class="{{ bodyClass }}">

        <!--Navigation-->
        {% block navmenu %}
            {% include 'nav.html' %}
        {% endblock %}

        <div class="container-fluid">
            <div class="content">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert-dismissable fade-show alert
                                    {% if message.level_tag == 'error' %}
                                        alert-danger
                                    {% else %}
                                        alert-{{ message.level_tag }}
                                    {% endif %}
                                ">

                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                    {{ message }}
                                    
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                {% block content %}

                {% endblock %}
            </div>
        </div>
        {% block outside_container_content %}
        {% endblock %}

        {% block footer_scripts %}
            <script src="{% static 'scripts/main.js' %}"></script>
        {% endblock %}
    </body>
</html>

mentorcoin_app/templates/base2.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block head_title %}MentorCoin{% endblock %}</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}

    {% block config %}
      <script>
        var activeNav;
      </script>
    {% endblock %}

    {% block head_links %}
        <link rel="stylesheet" href="{% static 'vendor/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
        <script src="{% static 'vendor/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'vendor/bignumber.js' %}"></script>
    {% endblock %}


    </head>
    <body style="padding-top:0px">

        <div class="container-fluid">
            <div class="content">
                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        {% if messages %}
                            {% for message in messages %}
                                <div class="alert
                                    {% if message.level_tag == 'error' %}
                                        alert-danger
                                    {% else %}
                                        alert-{{ message.level_tag }}
                                    {% endif %}
                                ">
                                    <p>{{ message }}</p>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                {% block content %}

                {% endblock %}
            </div>
        </div>
        {% block outside_container_content %}
        {% endblock %}

        {% block footer_scripts %}
            <script src="{% static 'scripts/main.js' %}"></script>
        {% endblock %}
    </body>
</html>

mentorcoin_app/templates/code_review_detail.html
{%  extends "base.html" %}
{% load static %}


{% block content %}
    <div class="row">
        <div style="margin: auto; width: 50%">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3>{{ object.pr_title }}</h3>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            <p style="padding-top: 25px"><strong>Code Review URL:</strong> 
                                <a href="{{ object.pr_url }}">
                                    {{object.pr_url}}
                                </a>
                            </p>
                            <p><strong>Code Review Requested By:</strong> 
                                <a href="https://github.com/{{ object.github_username }}">
                                    {{ object.github_username }}
                                </a>
                            </p>
                            <p><strong>Amount (ETH): </strong> {{object.amount|floatformat:3}} </p>
                            <p><strong>Description: </strong> {{object.description}}</p>
                            <p><strong>Keywords: </strong> {{object.keywords}}</p>
                            <p><strong>Expires In: </strong> {% widthratio object.expires 3600 1 %} hour(s) </p>
                            <p><strong>Experience Level: </strong> {{object.experience_level}}</p>   
                            <p><strong>Project Length: </strong> {{object.project_length}}</p>     
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>
{% endblock %}

mentorcoin_app/templates/code_review_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row" style="margin-bottom: 30px;">
    <div class="col-lg-9">
        <h2 style="width: 1632px; text-align: center">Create New Code Review Request</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6" style="margin: auto">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="text-danger col-xs-12">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <form id="code-review-create" action="{{ action }}" method="post" enctype="multipart/form-data">
            {% load widget_tweaks %}
            {% csrf_token %}

            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}

            {% for field in form.visible_fields %}
                <div class="form-group">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p class="text-danger col-xs-12">{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}
                    <label class="label-control col-sm-6" style="padding-left: 115px" for="{{ field.auto_id }}">
                        {{ field.label }}
                        {% if field.field.required %}<span class="text-danger">*</span>{% endif %}

                    </label>
                    <div class="col-sm-9" style="margin: auto">
                        {{ field|add_class:'form-control' }}
                    </div>
                </div>
            {% endfor %}
            <div class="col-sm-offset-3" style="margin-top:30px; text-align: center">
                <input class="form-control btn btn-primary" style="width: 180px" type="submit" value="Submit Code Review!" />
            </div>
        </form>
        {{ form.media }}
    </div>
</div>


<div class="bufficorn-modal" style="display: none">
    <div class="bufficorn-modal__content">
        <img class="bufficorn" src="{% static 'images/bufficorn.gif' %}">
        <h2 class="js-loading-text">Sending bounty data to IPFS...</h2>
    </div>
</div>

{% endblock %}

{% block footer_scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/ipfs-js.js' %}"></script>
    <script src="{% static 'scripts/ipfs.js' %}"></script>
    <script src="{% static 'scripts/code_review_create.js' %}"></script>
{% endblock %}

mentorcoin_app/templates/code_review_fulfill_form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="row" style="margin-bottom: 30px;">
    <div class="col-lg-9">
        <h2>Fulfill Code Review Request</h2>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="text-danger col-xs-12">{{ error }}</p>
            {% endfor %}
        {% endif %}
        <form id="code-review-fulfill" action="" method="post" enctype="multipart/form-data">
            {% load widget_tweaks %}
            {% csrf_token %}

            {% for field in form.hidden_fields %}
                {{ field }}
            {% endfor %}

            <p>Fulfilling Code Review Request for PR: <a href="{{ code_review.pr_url }}">{{ code_review.pr_title }}</a>

            <p>Please describe how you helped mentor the submitting user:</p>

            {% for field in form.visible_fields %}
                <div class="form-group">
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p class="text-danger col-xs-12">{{ error|escape }}</p>
                    {% endfor %}
                {% endif %}
                    <label class="label-control col-sm-6" for="{{ field.auto_id }}">
                        {{ field.label }}
                        {% if field.field.required %}<span class="text-danger">*</span>{% endif %}
                    </label>
                    <div class="col-sm-9">
                        {{ field|add_class:'form-control' }}
                    </div>
                </div>
            {% endfor %}
            <div class="col-sm-offset-3" style="margin-top:30px">
                <input class="form-control btn btn-primary" type="submit" value="Submit" />
            </div>
        </form>
        {{ form.media }}
    </div>
</div>


<div class="bufficorn-modal" style="display: none">
    <div class="bufficorn-modal__content">
        <img class="bufficorn" src="{% static 'images/bufficorn.gif' %}">
        <h2 class="js-loading-text">Sending bounty data to IPFS...</h2>
    </div>
</div>

{% endblock %}

{% block footer_scripts %}
    {{ block.super }}
    <script src="{% static 'scripts/ipfs-js.js' %}"></script>
    <script src="{% static 'scripts/ipfs.js' %}"></script>
    <script src="{% static 'scripts/code_review_fulfill.js' %}"></script>
{% endblock %}

mentorcoin_app/templates/code_review_list.html
{%  extends "base.html" %}
{% load static %}


{% block content %}
    <div>
        <div>
            <div>

                <ul class="nav nav-pills" id="myTab" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link active" id="open-tab" data-toggle="tab" href="#open" role="tab" aria-controls="open" aria-selected="true">Open <span class="badge badge-light">{{ view.total_number_open }}</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="claimed-tab" data-toggle="tab" href="#claimed" role="tab" aria-controls="claimed" aria-selected="false">Claimed <span class="badge badge-light">{{ view.total_number_claimed }}</span></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" id="closed-tab" data-toggle="tab" href="#closed" role="tab" aria-controls="closed" aria-selected="false">Closed</a>
                  </li>
                </ul>
                <div class="tab-content" id="myTabContent">

                  <div class="tab-pane fade show active" id="open" role="tabpanel" aria-labelledby="open-tab">
                      <div style="margin-top: 50px">
                        <h2 style="display: inline">Open Code Review Requests  </h2>
                        <h4 style="display: inline">({{ view.total_number_open }} worth {{ view.total_amount_open }} ETH)</h4>
                      </div>

                    <table class="table table-striped table-hover" style="width: 100%; margin-top: 25px">
                        <tr style="background: white; font-size: 24px">
                            <th>Pull Request Title</th>
                            <th>URL</th>
                            <th>Submitted By</th>
                            <th>Amount (ETH)</th>
                            <th></th>
                        </tr>
                    
                    {% for object in codereview_list %}
                        {% if object.status == 'open' %}
                            <tr>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="/code-review/detail/{{ object.pk }}">
                                        {{ object.pr_title }}
                                    </a>
                                </td>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="{{ object.pr_url }}">
                                        {{ object.pr_url }}
                                    </a>
                                </td>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="https://github.com/{{ object.submitted_by.username }}">
                                        {{ object.submitted_by.username }}
                                    </a>
                                </td>
                                <td style="padding-left: 25px; padding-top: 15px; vertical-align: middle">{{ object.amount }}</td>
                                <td>
                                    {% if request.user.socialaccount_set.all.0 %}
                                        <a href="{% url 'claim_code_review' object.pk %}" class="btn btn-primary btn-sm">Claim</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    </table>
                  </div>
                  <div class="tab-pane fade" id="claimed" role="tabpanel" aria-labelledby="claimed-tab">
                                      <div style="margin-top: 50px">
                    <h2 style="display: inline">Claimed Code Review Requests  </h2>
                    <h4 style="display: inline">({{ view.total_number_claimed }} worth {{ view.total_amount_claimed }} ETH)</h4>
                </div>

                    <table class="table table-striped table-hover" style="width: 100%; margin-top: 25px">
                        <tr style="background: white; font-size: 24px">
                            <th>Pull Request Title</th>
                            <th>URL</th>
                            <th>Submitted By</th>
                            <th>Claimed By</th>
                            <th>Amount (ETH)</th>
                            <th></th>
                        </tr>
                    
                    {% for object in codereview_list %}
                        {% if object.status == 'claimed' %}
                            <tr>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="/code-review/detail/{{ object.pk }}">
                                        {{ object.pr_title }}
                                    </a>
                                </td>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="{{ object.pr_url }}">
                                        {{ object.pr_url }}
                                    </a>
                                </td>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="https://github.com/{{ object.submitted_by.username }}">
                                        {{ object.submitted_by.username }}
                                    </a>
                                </td>
                                <td style="padding-top: 15px; vertical-align: middle">
                                    <a href="https://github.com/{{ object.claimed_by.username }}">
                                        {{ object.claimed_by.username }}
                                        <img style="width:20px" src="{{ object.claimed_by.socialaccount_set.all.0.get_avatar_url }}">
                                    </a>
                                </td>
                                <td style="padding-left: 25px; padding-top: 15px; vertical-align: middle">{{ object.amount }}</td>
                                <td>
                                    {% if request.user.socialaccount_set.all.0 and request.user == object.claimed_by %}
                                        <a href="{% url 'unclaim_code_review' object.pk %}" class="btn btn-warning btn-sm">Unclaim</a>
                                        <a href="{% url 'fulfill_code_review' object.pk %}" class="btn btn-success btn-sm">Fulfill</a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endif %}
                    {% endfor %}

                    </table>
                  </div>
                  <div class="tab-pane fade" id="closed" role="tabpanel" aria-labelledby="closed-tab">
                      
                  </div>
                </div>

            </div>
        </div>
</div>
{% endblock %}

mentorcoin_app/templates/main.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<style>
body.home {
    /* The image used */
    background-image: url("{% static 'images/Background17.jpg' %}");

    /* Set a specific height */
    height: 2000px;

    /* Create the parallax scrolling effect */
    background-attachment: fixed;
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

.col-centered {
    float: none;
    margin: 0 auto;
}


</style>
<style> #header { display: none } </style>
<div class="parallax">

	<div class="row">
		
		<div class="col-xs-12 col-centered">
			<img style="width: 100%" src="{% static 'images/logo_transparent.png' %}">
		</div>
	</div>
	<div class="row" style="padding-top: 60px">
		<div class="col-xs-12 col-centered">
			<img style="width: 100%" src="{% static 'images/git_together.png' %}">
		</div>
	</div>
	<div class="row" style="padding-top: 60px">
		<div class="col-xs-6 col-centered">
				<img style="width: 100%" src="{% static 'images/senior_dev_quote.png' %}">			
		</div>
			<div class="col-xs-6 col-centered">
				<img style="width: 100%" src="{% static 'images/junior_dev_quote.png' %}">			
		</div>
	</div>
		  
	  
</div>
{% endblock %}

mentorcoin_app/templates/nav.html
{% load static %}
{% load socialaccount %}


<div class="navbar navbar-expand-lg fixed-top navbar-dark bg-primary">
      <div class="container" style="margin-left: 0px; padding-left: 0px">
        <a href="/" style="width: 260px"> 
          <img style="width: 100%" src="{% static 'images/logo_transparent.png' %}">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
          
            <li class="nav-item" >
              <a class="nav-link" href="{% url 'code_review_create' %}" style="padding-left: 100px">Create New Code Review Request</a>
            </li>

            <li class="nav-item" style="padding-left: 50px">
              <a class="nav-link" href="{% url 'code_review_list' %}"> Code Review List</a>
            </li>

          </ul>

        </div>

        {% if request.user.socialaccount_set.all.0 %}
        <div class="nav-text" style="padding-left: 10px; position: absolute; right: 150px;  color: #fff">
          Welcome, {{ request.user}}!
          {{ request.user.email }}
        </div>

        <img style="height:50px; padding-left:10px; position: absolute; right: 75px" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />

        <div class="nav-text" style="text-align: right; color: #fff;padding-left:20px; width: 25px; position: absolute; right: 50px">
              <a href="/accounts/logout/" style="color: #fff; padding-right: 50px">Sign Out</a>
              {{ request.user.email }}
        </div>

        {% else %}
          <a class="btn btn-social btn-github" href="{% provider_login_url "github" %}" style="position: absolute; right: 25px">
            <span class="fab fa-github"></span> Sign in with GitHub
          </a>
        {% endif %}

      </div>
    </div>